apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "geth-swap.fullname" . }}-setupcontracts
  labels:
    {{- include "geth-swap.labels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
      - name: setup
        image: bash:3.2
        env:
          - name: BACKEND
            value: "http://{{ include "geth-swap.fullname" . }}:8545"
          - name: BZZACCOUNTS
            value: {{ .Values.swap.bzzaccounts | join " " }}
        command:
          - sh
          - -ac
          - >
            apk add --no-cache jq curl;
            curl https://gist.githubusercontent.com/ralph-pichler/dc0386f81ffa09c220271d4389b4a139/raw -o deploy.sh;
            while curl $BACKEND; do sleep 1; done;
            bash deploy.sh
      restartPolicy: Never
  backoffLimit: 1
